### PR TITLE
South Africa - Erick Mulindi - JS core 1-3 - week 8

### PR DESCRIPTION
**Pull request by mulindierick**
finsihes all coursework home work and exercises

# Your Details

- Your Name: Erick Mulindi
- Your City: South Africa
- Your Slack Name: Erick Mulindi

# Homework Details

- Module: JS Core 1
- Week: 3

### CODE REVIEW

**Review by sinopungula — COMMENTED** [review]
Reviewed your work, good job.

**Comment by Jontas77** [comment]
Hi Erick I reviewed your work, looking good, keep up the great work!

**Review by ezekiel444 — CHANGES_REQUESTED** [review]
exercise/J-string-substing/exercise2 imagine the names are two thousand. How do you plan on doing it this way?  possible solution: you loop through the names then split by space which will return an array then get the first index of the array.

**Review by ezekiel444 — CHANGES_REQUESTED** [review]
same problem of hard coding in i-string-replace

**Pull request closed without merging**
